default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
    run_tests(
      scheme: "DehSwiftUI",
      project: "DehSwiftUI.xcodeproj",
      devices: ["iPhone 15"]
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta_deh_mini do
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT'],
      is_key_content_base64: true
    )

    # 👇 這步是讓 CI 那台機器拿到 cert + provisioning profile
    match(
      type: "appstore",
      app_identifier: "edu.NCKU.new-deh-mini-II",
      readonly: true
    )

    build_app(
      scheme: "DEH Mini II",                # 👈 指定要打包哪一個 target 的 scheme
      project: "DehSwiftUI.xcodeproj",
      export_method: "app-store"
    )

    upload_to_testflight(
      app_identifier: "edu.NCKU.new-deh-mini-II" 
    )
  end
end
